data:
  root_dir: ~

  folder:
    cif: cif
    graph: graph
    spgraph: spgraph
    gemnet: gemnet
    spgemnet: spgemnet

  csv:
    matid: ~

  json:
    matid2idx: matid2idx # used to gather information from different device, we need to conver the list of str to tensor
    matidx2id: matidx2id

  # for crystal
  structure:
    min_lat_len: 8.0
    max_lat_len: ~
    max_num_atoms: ~

  spnode:
    enabled: true
    z: 120
    num: 8
    sample: grid # Literal['uniform', 'inverse_density']
    repulsion_distance: 1.0
    kde_bandwidth: 1.0

  pbc: true
  override: false
  num_process: 16

train:
  task_name: ~ # str: e.g. adsorption, should have a corresponding column in csv
  task_type: ~ # Literal["Regression", "BinaryClassification"]
  cls_num: ~ # for classification task, number of classes
  head_layers: 5 # for large model like JMP, more layers are recommended

  max_epochs: 300
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  accumulate_grad_batches: 1
  precision: 16-mixed
  log_every_n_steps: 20
  gradient_clip_val: 1.0
  batch_size: 8
  num_workers: 8

  loss_weight: ~ # Dict: e.g. {"task": 1.0, "site_offset": 1.0...}

  device: [0]
  log_dir: ./lightning_logs
  ckpt_path: ~
  resume: ~

optimize:
  type: jmp # recommended for GNN-series model

  transformer:
    optim_type: "adamw"
    lr: 0.0001
    weight_decay: 0.1
    decay_power: "cosine"
    warmup_steps: 0.1
    max_steps: -1
    end_lr: 1.0e-7

  reduce_on_plateau:
    optim_type: "adamw"
    lr: 0.001
    weight_decay: 0.1
    end_lr: 1.0e-6
    lr_monitor: val_loss
    monitor_mode: min
    lr_patience: 10
    lr_factor: 0.8
    lr_threshold: 1.0e-4

logger:
  enabled: true
  log_dir: ./logs
  filename: spatialread.log
  format: "%(asctime)s - %(levelname)s - %(message)s"
  level: DEBUG

model:
  gnn: painn
  head: transformer # Literal['transformer', 'spnode_mlp', 'atom_mlp']
  mp_between_spnode: false

  head_mlp:
    nlayers: 3
    hid_dim: 128 # should be the same as gnn's feature dimension, most gnns use 128
    readout: mean
    pool_feature: false

  transformer:
    nlayers: 6
    hid_dim: 128
    nheads: 12
    ff_dim: 512
    dropout: 0.15
    batch_first: true

  painn:
    n_atom_basis: 128
    n_interactions: 6
    shared_interactions: False
    shared_filters: False
    epsilon: 1.0e-8
    nuclear_embedding: ~
    electronic_embeddings: ~
    cutoff: 6.0
    max_num_neighbors: 30
    jumping_knowledge: ~

  gemnet:
    hid_dim: 256
    ckpt: ./ckpt/jmp/jmp-s.pt
    scale_file: ./spatialread/modules/gemnet/scale_files/small.pt

  visnet:
    # lmax: 2
    # vecnorm_type: ~
    # trainable_vecnorm: false
    # num_heads: 8
    # num_layers: 6
    # hidden_channels: 256
    # num_rbf: 32
    # trainable_rbf: false
    # # NOTE
    # max_z: 125
    # cutoff: 19.0
    # max_num_neighbors: 20
    # vertex: false
    # atomref: ~
    # reduce_op: sum
    # # mean: 0
    # # std: 1
    # derivative: false

    lmax: 2
    vecnorm_type: ~
    trainable_vecnorm: false
    num_heads: 8
    num_layers: 4
    hidden_channels: 128
    num_rbf: 32
    trainable_rbf: false
    max_z: 125
    cutoff: 4.0
    max_num_neighbors: 32
    vertex: false
    atomref: ~
    reduce_op: mean
    # mean: 0
    # std: 1
    derivative: false
