data:
  root_dir: ~

  folder:
    cif: cif
    graph: graph
    spgraph: spgraph
    gemnet: gemnet

  csv:
    matid: ~


  json: ~

  # for crystal
  structure:
    min_lat_len: 8.0 
    max_lat_len: ~
    max_num_atoms: ~

  spnode:
    sample: uniform # Literal['uniform', 'inverse_density']
    repulsion_distance: 1.0
    z: 120
    num: 512

  override: false
  num_process: 16

train:
  task_name: ~ # str: e.g. adsorption, should have a corresponding column in csv
  task_type: ~ # Literal["Regression", "BinaryClassification"]
  cls_num: ~ # for classification task, number of classes
  head_layers: 5 # for large model like JMP, more layers are recommended

  max_epochs: 300
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  accumulate_grad_batches: 1
  precision: 16-mixed
  log_every_n_steps: 20
  gradient_clip_val: 1.0
  batch_size: 8
  num_workers: 8

  loss_weight: ~ # Dict: e.g. {"task": 1.0, "site_offset": 1.0...}

  device: [0]
  log_dir: ./lightning_logs
  ckpt_path: ~
  resume: ~

optimize:
  type: jmp # recommended for GNN-series model

  transformer:
    optim_type: "adamw"
    lr: 0.0001
    weight_decay: 0.01
    decay_power: "cosine"
    warmup_steps: 0.1
    max_steps: -1
    end_lr: 1.0e-7

  reduce_on_plateau:
    optim_type: "adamw"
    lr: 0.001
    weight_decay: 0.01
    end_lr: 1.0e-6
    lr_monitor: val_loss
    monitor_mode: min
    lr_patience: 10
    lr_factor: 0.8
    lr_threshold: 1.0e-4

  jmp:
    lr_scheduler:
      last_step: -1
      max_epochs: 32
      max_steps: null
      min_lr_factor: 0.1
      name: warmup_cos_rlp
      rlp:
        cooldown: 0
        eps: 1.0e-08
        factor: 0.8
        frequency: 1
        interval: epoch
        min_lr: 0.0
        mode: min
        monitor: null
        name: rlp
        patience: 3
        threshold: 0.0001
        threshold_mode: rel
        warmup: null
      should_restart: false
      warmup_epochs: 2
      warmup_start_lr_factor: 0.1
      warmup_steps: null
    optimizer:
      amsgrad: false
      betas: !!python/tuple
      - 0.9
      - 0.95
      eps: 1.0e-08
      lr: 0.0001
      name: adamw
      weight_decay: 0.01
    parameter_specific_optimizers:
      - lr_scheduler:
          last_step: -1
          max_epochs: 300
          max_steps: null
          min_lr_factor: 0.25
          name: warmup_cos_rlp
          rlp:
            cooldown: 0
            eps: 1.0e-08
            factor: 0.8
            frequency: 1
            interval: epoch
            min_lr: 0.0
            mode: min
            monitor: null
            name: rlp
            patience: 3
            threshold: 0.0001
            threshold_mode: rel
            warmup: null
          should_restart: false
          warmup_epochs: 5
          warmup_start_lr_factor: 0.1
          warmup_steps: null
        name: null
        optimizer:
          amsgrad: false
          betas: !!python/tuple
          - 0.9
          - 0.95
          eps: 1.0e-08
          lr: 1.0e-04
          name: adamw
          weight_decay: 0.01
        paremeter_patterns:
        - torchmdnet.*
        - visnet.*

logger:
  enabled: true
  log_dir: ./logs
  filename: spatialread.log
  format: '%(asctime)s - %(levelname)s - %(message)s'
  level: DEBUG

model:
  gnn: painn
  head: transformer # Literal['transformer', 'spnode_mlp', 'atom_mlp']

  head_mlp:
    nlayers: 3
    hid_dim: 128 # should be the same as gnn's feature dimension, most gnns use 128
    readout: mean

  transformer:
    nlayers: 6
    hid_dim: 128
    nheads: 12
    ff_dim: 512
    dropout: 0.15
    batch_first: true

  painn:
    n_atom_basis: 128
    n_interactions: 6
    shared_interactions: False
    shared_filters: False
    epsilon: 1.0e-8
    nuclear_embedding: ~
    electronic_embeddings: ~
    cutoff: 6.0
    max_num_neighbors: 30

  gemnet:
    hid_dim: 256
    ckpt: ./ckpt/jmp/jmp-s.pt

  visnet:
    # lmax: 2
    # vecnorm_type: ~
    # trainable_vecnorm: false
    # num_heads: 8
    # num_layers: 6
    # hidden_channels: 256
    # num_rbf: 32
    # trainable_rbf: false
    # # NOTE
    # max_z: 125
    # cutoff: 19.0
    # max_num_neighbors: 20
    # vertex: false
    # atomref: ~
    # reduce_op: sum
    # # mean: 0
    # # std: 1
    # derivative: false

    lmax: 2
    vecnorm_type: ~
    trainable_vecnorm: false
    num_heads: 8
    num_layers: 4
    hidden_channels: 128
    num_rbf: 32
    trainable_rbf: false
    max_z: 125
    cutoff: 4.0
    max_num_neighbors: 32
    vertex: false
    atomref: ~
    reduce_op: mean
    # mean: 0
    # std: 1
    derivative: false
